### PR TITLE
topojson bugs fix

### PR DESCRIPTION
**Pull request by meule**

### CODE REVIEW

**Comment by meule** [comment]
topojson bugs fix

**Comment by devTristan** [comment]
Which bug?

Also, on line 11, please declare `tileOffset` with `var`

**Comment by meule** [comment]
1. Include topojson.js  in example.
2. Set *tileOffset* variable in *projections.WGS84*
3. When you call *var result = mode.parse(xhr.response, canvas)* for topojson, there is no *response* field in xhr object. It's because *var xhr = d3.json(url, callback)* calls callback with data object in xhr not in xhr.response.

**Comment by devTristan** [comment]
:+1: 

Thanks for contributing!

**Pull request merged**
